#!/bin/bash

# Auto-Build Environment Setup for SQLAlchemy Models Generation
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check if Docker is running
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}Docker is not running. Please start Docker first.${NC}"
    exit 1
fi
echo -e "${GREEN}Docker is running${NC}"

# Check if Supabase containers are running
if ! docker ps | grep -q "supabase"; then
    echo -e "${YELLOW}Supabase containers not detected. Starting via docker/start.sh...${NC}"
    if [ -f "./docker/start.sh" ]; then
        ./docker/start.sh
        sleep 5
    else
        echo -e "${RED}docker/start.sh not found. Please start Supabase manually.${NC}"
        exit 1
    fi
fi
echo -e "${GREEN}Supabase containers running${NC}"

# Check for .env file
if [ ! -f ".env" ]; then
    echo -e "${YELLOW}Warning: .env file not found. Database connection may fail.${NC}"
fi

# ============================================
# VERIFY DATABASE CONNECTION
# ============================================

echo ""
echo "Verifying database connection..."

cd app

python -c "
from database.database_utils import DatabaseUtils
from sqlalchemy import create_engine, text

try:
    engine = create_engine(DatabaseUtils.get_connection_string())
    with engine.connect() as conn:
        result = conn.execute(text('SELECT 1'))
        print('Database connection successful')
except Exception as e:
    print(f'Database connection failed: {e}')
    exit(1)
" || exit 1

cd ..

echo -e "${GREEN}Database connection verified${NC}"

# ============================================
# CHECK ALEMBIC CONFIGURATION
# ============================================

echo ""
echo "Checking Alembic configuration..."

if [ ! -f "app/alembic.ini" ]; then
    echo -e "${RED}app/alembic.ini not found. Alembic is not configured.${NC}"
    exit 1
fi

if [ ! -d "app/alembic" ]; then
    echo -e "${RED}app/alembic directory not found. Alembic is not configured.${NC}"
    exit 1
fi

echo -e "${GREEN}Alembic configuration found${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Database: PostgreSQL (Supabase) on localhost:54322"
echo "  Backend:  FastAPI on localhost:8000 (not started)"
echo ""
echo "To work on this spec:"
echo "  1. Models will be created in: app/database/models/"
echo "  2. Generate migrations with: cd app && ./makemigration.sh"
echo "  3. Apply migrations with: cd app && ./migrate.sh"
echo ""
echo "Schema documentation in:"
echo "  ai_docs/context/source_docs/schema/"
echo ""
echo "Reference pattern file:"
echo "  app/database/event.py"
echo ""
